### ISSUE TITLE
Firebase AdMob + AudioPlayers duplicate symbol error

### ISSUE THREAD

**Issue by IAmKio** [luanpotter/audioplayer#34]
Hi there,

I've been messing around with this for a few hours now trying to fix this issue, but i've noticed that when both Firebase AdMob (`firebase_admob: ^0.5.7`) and AudioPlayers (`audioplayers: ^0.7.5`) are both installed - when building to run, i get the following error:

```
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
duplicate symbol __channel in:
/Users/k/Development/mobile/app/build/ios/Debug-iphonesimulator/audioplayers/libaudioplayers.a(AudioplayersPlugin.o)
/Users/k/Development/mobile/app/build/ios/Debug-iphonesimulator/firebase_admob/libfirebase_admob.a(FLTMobileAd.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Could not build the application for the simulator.
Error launching application on iPhone X.
Exited (sigterm)
```
**It's worth noting that i have also tried the inverse - i removed Firebase AdMob and left in AudioPlayers - and everything builds as expected.** It appears that `__channel` is to blame here, but i'm unsure where to find this variable / symbol so i could possibly test a change to it.

FYI here's my Flutter Doctor report:

```
[✓] Flutter (Channel master, v0.7.2-pre.18, on Mac OS X 10.13.6 17G65, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.25.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
```
I've tried upgrading all Firebase packages, `flutter clean`, i've also reinstalled Flutter just incase.

Any direction or help on the matter would be greatly appreciated.

**Comment by ckildgypmk** [comment]
Same here. Anyone know how to fix this?

**Comment by luanpotter** [comment]
I updated the SDK version as mentioned on the issue linked, in order to work with Dart 2.1. Can @IAmKio and @ckildgypmk confirm it still a problem?

Otherwise might be a name clash with the `__channel` variable name on the Objective-C code. In that case, someone can help out renaming that to something more unique to audioplayers plugin to see if it stops conflicting with admob. If you could contribute with a PR, would be awesome! I don't have any iOS devices to test with.

**Comment by robertkhs** [comment]
Same problem here. ㅠ.ㅠ;
Firebase AdMob (firebase_admob: ^0.6.1) and AudioPlayers (audioplayers: ^0.7.6)  are both installed - when building to run, I get same error.(only in IOS side not in Android)

I can release my app if 'only' this problem is solved.  

anyone plz help me out.

**Comment by imtaehyun** [comment]
@luanpotter I made pull request #49
both audioplayers and firebase_admob use _channel for variable name, so i changed it from audioplayers'. it worked!

**Comment by luanpotter** [comment]
Thanks, @imtaehyun !

**Comment by Tareque16** [comment]
The solution is in your plugins pubspec.yaml. Just change the environment sdk setup please

```
environment:
sdk: ">=2.0.0-dev.58.0 <3.0.0"``
```
